In [1]:
import pandas as pd
import duckdb

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

In [3]:
df=pd.read_csv(r"C:\Users\TOSHIBA\Desktop\raw_data.csv")

In [4]:
df.columns

Index(['vehicleNumber', 'class', 'vehicleManufacturerName', 'model',
       'vehicleColour', 'type', 'owner', 'ownerFatherName', 'regAuthority',
       'regDate', 'regNo', 'presentAddress', 'rcExpiryDate', 'rcTaxUpto',
       'vehicleInsuranceCompanyName', 'permanentAddress',
       'vehicleManufacturingMonthYear', 'vehicleInsuranceUpto',
       'vehicleCubicCapacity', 'grossVehicleWeight', 'rcFinancer',
       'vehicleCategory', 'vehicleTaxUpto', 'rcStandardCap',
       'vehicleCylindersNo', 'vehicleSeatCapacity', 'splitPermanentAddress',
       'splitPresentAddress', 'normsType', 'bodyType', 'ownerCount',
       'mobileNumber', 'status', 'statusAsOn', 'unladenWeight',
       'rcStandardCap.1', 'vehicleSleeperCapacity', 'vehicleStandingCapacity',
       'wheelbase', 'puccUpto', 'blacklistStatus', 'permitIssueDate',
       'permitNumber', 'permitType', 'permitValidFrom', 'permitValidUpto',
       'nonUseStatus', 'nonUseFrom', 'nonUseTo', 'nationalPermitNumber',
       'nationalPermitUpto', 'nationalPermitIssuedBy', 'isCommercial',
       'nocDetails', 'error'],
      dtype='object')

In [5]:
df.head(7)

,vehicleNumber,class,vehicleManufacturerName,model,vehicleColour,type,owner,ownerFatherName,regAuthority,regDate,regNo,presentAddress,rcExpiryDate,rcTaxUpto,vehicleInsuranceCompanyName,permanentAddress,vehicleManufacturingMonthYear,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleTaxUpto,rcStandardCap,vehicleCylindersNo,vehicleSeatCapacity,splitPermanentAddress,splitPresentAddress,normsType,bodyType,ownerCount,mobileNumber,status,statusAsOn,unladenWeight,rcStandardCap.1,vehicleSleeperCapacity,vehicleStandingCapacity,wheelbase,puccUpto,blacklistStatus,permitIssueDate,permitNumber,permitType,permitValidFrom,permitValidUpto,nonUseStatus,nonUseFrom,nonUseTo,nationalPermitNumber,nationalPermitUpto,nationalPermitIssuedBy,isCommercial,nocDetails,error
0,5,M-Cycle/Scooter,BAJAJ AUTO LTD,PULSAR 150 DTSI,COCKT. WINE RED,PETROL,VIKAS CHAUHAN,NaN,"ALIGARH RTO, UTTAR PRADESH",12-01-2015,UP81BB9866,"H.NO.204,VILL.KASIMPUR,KAURIYAGANJ,P.S.AKRABAD...",11-01-2030,NaN,ACKO GENERAL INSURANCE LIMITED,"H.NO.204,VILL.KASIMPUR,KAURIYAGANJ,P.S.AKRABAD...",NaN,10-09-2022,NaN,NaN,NaN,2WN,06-01-2030,NaN,NaN,NaN,"{""district"":[""ALIGARH""],""state"":[[""UTTAR PRADE...","{""district"":[""ALIGARH""],""state"":[[""UTTAR PRADE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),WHITE,PETROL,AASIM KHAN,SHAN AHMAD,"HAPUR, UTTAR PRADESH",18/04/2018,UP37J0858,"H.NO-01 MOHAMMADPUR RUSTAMPUR,TEH-GARHMUKTESHW...",17/04/2033,NaN,ACKO GENERAL INSURANCE LIMITED,"H.NO-01 MOHAMMADPUR RUSTAMPUR,TEH-GARHMUKTESHW...",09-2017,22/04/2023,159.7,267.0,NaN,2WN,NaN,0.0,1.0,2.0,"{""district"":[""GHAZIABAD""],""state"":[[""UTTAR PRA...","{""district"":[""GHAZIABAD""],""state"":[[""UTTAR PRA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,STAR CITY,BLACK,PETROL,MR KHURSHEED AHMAD,SHRI CHANDA KHAN,"KASHIPUR ARTO, UTTARAKHAND",29/11/2012,UK06Y1676,"NATHA SINGH JASPUR,U.S.N.0",28/11/2027,NaN,ACKO GENERAL INSURANCE LIMITED,"NATHA SINGH JASPUR,U.S.N.0",11-2012,21/09/2022,110.0,0.0,NaN,2WN,NaN,NaN,1.0,2.0,NaN,NaN,BHARAT STAGE III,SOLO,1.0,NaN,ACTIVE,02-08-2022,110.0,NaN,NaN,NaN,NaN,15/03/2022,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
3,12,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,RED,PETROL,RAKESH KUMAR,NaN,"MATHURA, Uttar Pradesh",29/09/2015,UP85AU2787,"SALAKA , SUHAGPUR NAUJHEEL,MATHURA, -999999",27/09/2030,NaN,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,"SALAKA , SUHAGPUR NAUJHEEL,MATHURA, -999999",NaN,24/09/2016,NaN,NaN,NaN,M-Cycle/Scooter(2WN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,BLUE,PETROL,ISMAIL,IDSHAH,"MATHURA, Uttar Pradesh",29/09/2015,UP85AU2788,DAUTANA CHHATA MATHURA Uttar Pradesh 999999,27/09/2030,NaN,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,DAUTANA CHHATA MATHURA Uttar Pradesh 999999,NaN,24/09/2016,100.0,NaN,NaN,M-Cycle/Scooter(2WN),NaN,NaN,NaN,NaN,NaN,NaN,BHARAT STAGE II,SOLO,1.0,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS XLHD,BLACK,PETROL,DHARAM SINGH,SH. SUKHI,"MATHURA, Uttar Pradesh",09-01-2015,UP85AQ7652,NAGLA SURIR MATHURA MATHURA Uttar Pradesh 999999,08-01-2030,NaN,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,NAGLA SURIR MATHURA MATHURA Uttar Pradesh 999999,10-2014,06-01-2016,70.0,205.0,On Cash,TWO WHEELER(NT),NaN,0.0,1.0,2.0,"{""district"":[""MATHURA""],""state"":[[""UTTAR PRADE...","{""district"":[""MATHURA""],""state"":[[""UTTAR PRADE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,BLACK GREEN,PETROL,MUNNA LAL,SH. REKHI,"MATHURA, UTTAR PRADESH",06-11-2013,UP85AL5245,"100 B RANVARI CHHATA,MATHURA,999999",05-11-2028,NaN,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,"100 B RANVARI CHHATA,MATHURA,999999",11-2013,30/10/2014,100.0,238.0,NaN,2WN,NaN,NaN,1.0,2.0,NaN,NaN,BHARAT STAGE II,SOLO,1.0,NaN,ACTIVE,02-08-2022,108.0,0.0,NaN,0.0,1250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN

In [6]:
columns = ['vehicleNumber', 'vehicleColour', 'owner', 'ownerFatherName', 'presentAddress', 'permanentAddress', 'rcStandardCap', 'splitPermanentAddress', 'splitPresentAddress', 'rcStandardCap.1', 'vehicleSleeperCapacity', 'vehicleStandingCapacity', 'wheelbase', 'error','nonUseFrom','nonUseTo','nationalPermitNumber','nationalPermitUpto','nocDetails','permitValidUpto','permitType','permitIssueDate','permitNumber','mobileNumber','rcTaxUpto','permitValidFrom','regNo','regAuthority']

In [7]:
df1=df.drop(columns=columns)

In [8]:
df1.columns

Index(['class', 'vehicleManufacturerName', 'model', 'type', 'regDate',
       'rcExpiryDate', 'vehicleInsuranceCompanyName',
       'vehicleManufacturingMonthYear', 'vehicleInsuranceUpto',
       'vehicleCubicCapacity', 'grossVehicleWeight', 'rcFinancer',
       'vehicleCategory', 'vehicleTaxUpto', 'vehicleCylindersNo',
       'vehicleSeatCapacity', 'normsType', 'bodyType', 'ownerCount', 'status',
       'statusAsOn', 'unladenWeight', 'puccUpto', 'blacklistStatus',
       'nonUseStatus', 'nationalPermitIssuedBy', 'isCommercial'],
      dtype='object')

In [9]:
duckdb.sql("SELECT distinct(isCommercial) FROM df1").df().head(5)

  isCommercial
0        False
1          NaN
2         True

# filling null values with None

In [10]:
df1.fillna('None',inplace=True)

# finding out how many days before insurance expiry or not

In [11]:
df1['insurance_expiry_date']=pd.to_datetime(df1['vehicleInsuranceUpto'],format='mixed')

In [12]:
df1['today_date']=pd.Timestamp.today().date()
df1['today_date']=pd.to_datetime(df1['today_date'])

In [13]:
df1['days']=(df1['insurance_expiry_date']-df1['today_date']).dt.days

In [14]:
df1.head(5)

,class,vehicleManufacturerName,model,type,regDate,rcExpiryDate,vehicleInsuranceCompanyName,vehicleManufacturingMonthYear,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleTaxUpto,vehicleCylindersNo,vehicleSeatCapacity,normsType,bodyType,ownerCount,status,statusAsOn,unladenWeight,puccUpto,blacklistStatus,nonUseStatus,nationalPermitIssuedBy,isCommercial,insurance_expiry_date,today_date,days
0,M-Cycle/Scooter,BAJAJ AUTO LTD,PULSAR 150 DTSI,PETROL,12-01-2015,11-01-2030,ACKO GENERAL INSURANCE LIMITED,None,10-09-2022,None,None,None,2WN,06-01-2030,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-10-09,2024-03-12,-520
1,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),PETROL,18/04/2018,17/04/2033,ACKO GENERAL INSURANCE LIMITED,09-2017,22/04/2023,159.7,267.0,None,2WN,None,1.0,2.0,None,None,None,None,None,None,None,None,None,None,None,2023-04-22,2024-03-12,-325
2,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,STAR CITY,PETROL,29/11/2012,28/11/2027,ACKO GENERAL INSURANCE LIMITED,11-2012,21/09/2022,110.0,0.0,None,2WN,None,1.0,2.0,BHARAT STAGE III,SOLO,1.0,ACTIVE,02-08-2022,110.0,15/03/2022,None,N,None,False,2022-09-21,2024-03-12,-538
3,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,27/09/2030,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,None,24/09/2016,None,None,None,M-Cycle/Scooter(2WN),None,None,None,None,None,1.0,None,None,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726
4,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,27/09/2030,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,None,24/09/2016,100.0,None,None,M-Cycle/Scooter(2WN),None,None,None,BHARAT STAGE II,SOLO,1.0,A,None,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726

# Dopping more unecessary columns

In [15]:
df1.drop(columns=['status','statusAsOn','vehicleTaxUpto','rcExpiryDate','vehicleManufacturingMonthYear'],inplace=True)

In [16]:
# rc expiry is independent of insurance expiry so it wont matter

In [17]:
df1.head(5)

,class,vehicleManufacturerName,model,type,regDate,vehicleInsuranceCompanyName,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleCylindersNo,vehicleSeatCapacity,normsType,bodyType,ownerCount,unladenWeight,puccUpto,blacklistStatus,nonUseStatus,nationalPermitIssuedBy,isCommercial,insurance_expiry_date,today_date,days
0,M-Cycle/Scooter,BAJAJ AUTO LTD,PULSAR 150 DTSI,PETROL,12-01-2015,ACKO GENERAL INSURANCE LIMITED,10-09-2022,None,None,None,2WN,None,None,None,None,None,None,None,None,None,None,None,2022-10-09,2024-03-12,-520
1,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),PETROL,18/04/2018,ACKO GENERAL INSURANCE LIMITED,22/04/2023,159.7,267.0,None,2WN,1.0,2.0,None,None,None,None,None,None,None,None,None,2023-04-22,2024-03-12,-325
2,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,STAR CITY,PETROL,29/11/2012,ACKO GENERAL INSURANCE LIMITED,21/09/2022,110.0,0.0,None,2WN,1.0,2.0,BHARAT STAGE III,SOLO,1.0,110.0,15/03/2022,None,N,None,False,2022-09-21,2024-03-12,-538
3,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,None,None,None,M-Cycle/Scooter(2WN),None,None,None,None,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726
4,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,100.0,None,None,M-Cycle/Scooter(2WN),None,None,BHARAT STAGE II,SOLO,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726

In [18]:
df[df['isCommercial']==True]

,vehicleNumber,class,vehicleManufacturerName,model,vehicleColour,type,owner,ownerFatherName,regAuthority,regDate,regNo,presentAddress,rcExpiryDate,rcTaxUpto,vehicleInsuranceCompanyName,permanentAddress,vehicleManufacturingMonthYear,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleTaxUpto,rcStandardCap,vehicleCylindersNo,vehicleSeatCapacity,splitPermanentAddress,splitPresentAddress,normsType,bodyType,ownerCount,mobileNumber,status,statusAsOn,unladenWeight,rcStandardCap.1,vehicleSleeperCapacity,vehicleStandingCapacity,wheelbase,puccUpto,blacklistStatus,permitIssueDate,permitNumber,permitType,permitValidFrom,permitValidUpto,nonUseStatus,nonUseFrom,nonUseTo,nationalPermitNumber,nationalPermitUpto,nationalPermitIssuedBy,isCommercial,nocDetails,error
388,604,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),T GREY,PETROL,RAJAT KUMAR,DINESH KUMAR,"Kasganj(kashi ram nagar), Uttar Pradesh",18/7/2018,UP87L2117,SALEMPUR URF BHOOTAL GANGAGARH SORON Kanshiram...,17/7/2033,NaN,Bajaj Allianz General Insurance Co. Ltd.,SALEMPUR URF BHOOTAL GANGAGARH SORON Kanshiram...,3-2018,02-12-2021,159.0,267.0,On Cash,TWO WHEELER(NT),NaN,NaN,1.0,2.0,NaN,NaN,BHARAT STAGE IV,2 WHEELER,2.0,NaN,ACTIVE,23/12/2022,137.0,0.0,0.0,0.0,1300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN

# getting age of vehicles

In [19]:
df1['car_register']=pd.to_datetime(df1['regDate'],format='mixed')

In [20]:
df1['car_age']=(df1['today_date']-df1['car_register']).dt.days

In [21]:
df1.head(5)

,class,vehicleManufacturerName,model,type,regDate,vehicleInsuranceCompanyName,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleCylindersNo,vehicleSeatCapacity,normsType,bodyType,ownerCount,unladenWeight,puccUpto,blacklistStatus,nonUseStatus,nationalPermitIssuedBy,isCommercial,insurance_expiry_date,today_date,days,car_register,car_age
0,M-Cycle/Scooter,BAJAJ AUTO LTD,PULSAR 150 DTSI,PETROL,12-01-2015,ACKO GENERAL INSURANCE LIMITED,10-09-2022,None,None,None,2WN,None,None,None,None,None,None,None,None,None,None,None,2022-10-09,2024-03-12,-520,2015-12-01,3024
1,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),PETROL,18/04/2018,ACKO GENERAL INSURANCE LIMITED,22/04/2023,159.7,267.0,None,2WN,1.0,2.0,None,None,None,None,None,None,None,None,None,2023-04-22,2024-03-12,-325,2018-04-18,2155
2,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,STAR CITY,PETROL,29/11/2012,ACKO GENERAL INSURANCE LIMITED,21/09/2022,110.0,0.0,None,2WN,1.0,2.0,BHARAT STAGE III,SOLO,1.0,110.0,15/03/2022,None,N,None,False,2022-09-21,2024-03-12,-538,2012-11-29,4121
3,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,None,None,None,M-Cycle/Scooter(2WN),None,None,None,None,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726,2015-09-29,3087
4,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,100.0,None,None,M-Cycle/Scooter(2WN),None,None,BHARAT STAGE II,SOLO,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726,2015-09-29,3087

In [22]:
def company(row):
    if row['vehicleManufacturerName'] in ['BAJAJ AUTO LTD', 'TVS MOTOR COMPANY LTD', 'HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD']:
        return 'Two_Wheeler'
    elif row['vehicleManufacturerName'] == 'VOLVO AUTO INDIA PVT LTD':
        return 'Four_Wheeler'
    else:
        return 'None'

In [23]:
df1['vehicle_type']=df1.apply(company,axis=1)

# getting vehicles with multiple owners

In [24]:
df1['ownerCount'].unique()

array(['None', 1.0, 3.0, 2.0], dtype=object)

In [25]:
def owner(row):
    if row['ownerCount']=='None':
        return 'single_owner'
    else:
        return 'multiple_owners'

In [26]:
df1['vehicle_ownership']=df1.apply(owner,axis=1)

In [27]:
df1.groupby('vehicle_ownership').size()

vehicle_ownership
multiple_owners     138
single_owner       1061
dtype: int64

In [36]:
def clean_model_name(model):
    # Convert to lowercase
    model = model.lower()
    # Remove special characters and extra spaces
    model = re.sub(r'[^a-zA-Z0-9\s]', '', model)
    model = model.strip()
    # Replace common variations with simplified names
    if 'apache' in model:
        return 'apache'
    elif 'jupiter' in model:
        return 'jupiter'
    elif 'ntorq' in model:
        return 'ntorq'
    elif 'sport' in model:
        return 'sport'
    elif 'star city' in model:
        return 'star city'
    elif 'xl100' in model:
        return 'xl100'
    elif 'victor' in model:
        return 'victor'
    elif 'radeon' in model:
        return 'radeon'
    elif 'phoenix' in model:
        return 'phoenix'
    elif 'pulsar' in model:
        return 'pulsar'
    elif 'ronin' in model:
        return 'ronin'
    elif 'raider' in model:
        return 'raider'
    elif 'xl' in model:
        return 'xl series'
    elif 'scotty' in model or 'zest' in model:
        return 'scotty'
    elif 'volvo' in model:
        return 'volvo'
    else:
        return 'other'

In [37]:
df1['cleaned_model']=df1['model'].apply(clean_model_name)

In [38]:
import re

In [43]:
df1['cleaned_model'].unique()

array(['pulsar', 'apache', 'star city', 'sport', 'xl series', 'phoenix',
       'raider', 'other', 'xl100', 'ntorq', 'jupiter', 'ronin', 'radeon',
       'victor', 'scotty', 'volvo'], dtype=object)

In [48]:
premium_models = ['pulsar', 'apache', 'ntorq', 'jupiter']
mass_market_models = ['star city', 'phoenix', 'xl series', 'raider', 'ronin', 'radeon','sport','victor']
car_model='volvo'

def categorize_model(cleaned_model):
    if cleaned_model in premium_models:
        return "Premium two-wheeler"
    elif cleaned_model in mass_market_models:
        return "Mass_market_two_wheeler"
    elif cleaned_model in car_model:
        return 'Premium_four_wheeler'
    else:
        return "Other category"

In [50]:
df1['vehicle_category1']=df1['cleaned_model'].apply(categorize_model)

In [51]:
df1.head(5)

,class,vehicleManufacturerName,model,type,regDate,vehicleInsuranceCompanyName,vehicleInsuranceUpto,vehicleCubicCapacity,grossVehicleWeight,rcFinancer,vehicleCategory,vehicleCylindersNo,vehicleSeatCapacity,normsType,bodyType,ownerCount,unladenWeight,puccUpto,blacklistStatus,nonUseStatus,nationalPermitIssuedBy,isCommercial,insurance_expiry_date,today_date,days,car_register,car_age,vehicle_type,vehicle_ownership,cleaned_model,vehicle_category1
0,M-Cycle/Scooter,BAJAJ AUTO LTD,PULSAR 150 DTSI,PETROL,12-01-2015,ACKO GENERAL INSURANCE LIMITED,10-09-2022,None,None,None,2WN,None,None,None,None,None,None,None,None,None,None,None,2022-10-09,2024-03-12,-520,2015-12-01,3024,Two_Wheeler,single_owner,pulsar,Premium two-wheeler
1,M-Cycle/Scooter,TVS MOTOR COMPANY LTD,TVS APACHE RTR 160 (BS IV),PETROL,18/04/2018,ACKO GENERAL INSURANCE LIMITED,22/04/2023,159.7,267.0,None,2WN,1.0,2.0,None,None,None,None,None,None,None,None,None,2023-04-22,2024-03-12,-325,2018-04-18,2155,Two_Wheeler,single_owner,apache,Premium two-wheeler
2,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,STAR CITY,PETROL,29/11/2012,ACKO GENERAL INSURANCE LIMITED,21/09/2022,110.0,0.0,None,2WN,1.0,2.0,BHARAT STAGE III,SOLO,1.0,110.0,15/03/2022,None,N,None,False,2022-09-21,2024-03-12,-538,2012-11-29,4121,Two_Wheeler,multiple_owners,star city,Mass_market_two_wheeler
3,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,None,None,None,M-Cycle/Scooter(2WN),None,None,None,None,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726,2015-09-29,3087,Two_Wheeler,multiple_owners,sport,Mass_market_two_wheeler
4,M-Cycle/Scooter(2WN),TVS MOTOR COMPANY LTD,TVS SPORT,PETROL,29/09/2015,ANY OTHERS/ NOT AVAILABLE/ EXEMPTED,24/09/2016,100.0,None,None,M-Cycle/Scooter(2WN),None,None,BHARAT STAGE II,SOLO,1.0,None,None,None,None,None,None,2016-09-24,2024-03-12,-2726,2015-09-29,3087,Two_Wheeler,multiple_owners,sport,Mass_market_two_wheeler

In [58]:
def renew(days):
    if days<=365:
        return 'High'
    elif days>365 and days<1095:
        return 'Medium'
    else:
        return 'Low'

In [61]:
df1['insurance_renewal']=df1['days'].apply(renew)

In [64]:
df1.groupby('insurance_renewal').size()

insurance_renewal
High        62
Low       1008
Medium     129
dtype: int64

In [66]:
df1['vehicle_category1'].unique()

array(['Premium two-wheeler', 'Mass_market_two_wheeler', 'Other category',
       'Premium_four_wheeler'], dtype=object)

In [67]:
df1['vehicle_ownership'].unique()

array(['single_owner', 'multiple_owners'], dtype=object)

In [91]:
def renew_probability(vehicle_ownership, vehicle_category1):
    if vehicle_ownership == 'single_owner':
        if vehicle_category1 == 'Premium two-wheeler' or vehicle_category1 == 'Premium_four_wheeler':
            return 'High'
        else:
            return 'Low'
    elif vehicle_ownership == 'multiple_owners' :
        if vehicle_category1 == 'Mass_market_two_wheeler' or vehicle_category1 == 'Premium two-wheeler' or vehicle_category1 == 'Premium_four_wheeler':
            return 'Medium'
        else:
            return 'Low'
    else:
        return 'Low'  
    
df1['renewal_probability'] = df1.apply(lambda row: renew_probability(row['vehicle_ownership'], row['vehicle_category1']), axis=1)

In [92]:
df1.groupby('renewal_probability').size()

renewal_probability
High      303
Low       780
Medium    116
dtype: int64

In [94]:
df1.groupby('insurance_renewal').size()

insurance_renewal
High        62
Low       1008
Medium     129
dtype: int64